### PR TITLE
Initial CMake support.

### PR DESCRIPTION
**Pull request by protomors**
It is still incomplete but with this CMake files I was able to generate solution and projects for Visual Studio 2017 and (with some manual steps) build a working executable. I was even surprised how easy this experiment went so far.
Now I want to hear an opinion of authors of Miranda NG about using CMake in this project. If there is a possibility that this will be merged I will try to complete it (add files for rest of plugins, test with different versions of Visual Studio). I think that with CMake build process will be more flexible and maintainable.

### CODE REVIEW

**Comment by Goraf** [comment]
If somehow someone will ever in the far far future try to start creating a basis for other platforms then CMake files would be a good startpoint. I'm not sure if they replace current VS-way of already created projects but for me they could coexist

**Comment by protomors** [comment]
>If somehow, someone will ever in the far far future try to start creating a basis for other platforms then CMake files would be a good startpoint.

I also had similar thoughts when started this. But, even if Miranda remains tied to Visual Studio, CMake have some benefits. If implemented right you wont need to maintain multiple versions of projects for different versions of VS. Now, as I understand, changes to projects structure have to be made manually to each version.

>I'm not sure if they replace current VS-way of already created projects but for me they could coexist

This is why I tried to add CMake without touching existing files. Developers will still be able to use existing VS solution and projects. But I hope that in the future this manually created projects can be replaces by automatically generated.

**Comment by protomors** [comment]
I am glad that reaction is positive. Then I will continue working on this. In case I will have some questions about build process where will be better to write them?

**Comment by Goraf** [comment]
You could try in one of jabber conference rooms:
- miranda-ng-int@conference.jabber.ru (international)
- miranda-ng@conference.jabber.ru (Russian)

or at forum. Ghazan is like a mastermind behind everything related to Miranda ;)

**Pull request merged**
