### PR TITLE
skypeWeb: Show user nicks instead of skypenames in chat windows

### PR DESCRIPTION
**Pull request by olegtarasov**

### CODE REVIEW

**Comment by MikalaiR** [comment]
IMHO, this is bad idea. It works only if contact in your contact list. Result - mix of nicks and skypenames in nicklist.

**Comment by olegtarasov** [comment]
Yes, this is the intended behavior. Skype logins are not informative at all. For example, I have a massive chat with 30+ members, some of those are on my contact list (those who post most frequently anyway). And most of those people have the most uninformative logins like “double.damage” for example. I've never seen this login before, and I don't know who is behind this login. I have to get this information from contact info and remember it for future reference. Not the information I'd like to remember, really :)

**Comment by olegtarasov** [comment]
So what about this pull request?

**Comment by tweimer** [comment]
@aunsane I agree with @olegtarasov , most people mainly chat with people on their contact list anyways. Maybe you could add an option for this behaviour?

@olegtarasov Looking over the code, I see that mir_a2t_cp leaks memory at several places, you need to wrap it in ptrT or mir_free it manually.

**Comment by Robyer** [comment]
I agree with proposed functionality too.

I had similar "problem" in Facebook's chats where it was hard to get names of users in the chatroom, so instead of showing their IDs I loaded name of users that we had in contact list (so it was mix of ids and names from clist). It was this way for a year or so and nobody complained about "inconsistency".

And this may provide another advantage - if you have some contact renamed in your local Miranda contact list, you could see the same custom name of that contact in chat too :)

**Comment by olegtarasov** [comment]
@tweimer Thanks for the tip! I fixed the memory leak in a new commit.

**Comment by olegtarasov** [comment]
Ok, so no one seems to be interested.

**Comment by Robyer** [comment]
I'm interested, but as I'm not maintainer of SkypeWeb I thought someone else will commit it.

If you could give me fresh PR, I'll revise it and merge it myself :)

**Comment by Robyer** [comment]
Ok, I still see your changes, so no need to creating new PR.

**Comment by Robyer** [comment]
Finally done :-)

See http://trac.miranda-ng.org/changeset/17211/
And bit related http://trac.miranda-ng.org/changeset/17212/

**Pull request closed without merging**
