### PR TITLE
SendSS: fixed uploadpie upload by using HTTPS

### PR DESCRIPTION
**Pull request by White-Tiger**
P.S. why is NETLIBHTTPREQUEST->szUrl non-const? Netlib shouldn't (and doesn't IIRC) write to it, just read.

### CODE REVIEW

**Comment by tweimer** [comment]
@georgehazan  why is NETLIBHTTPREQUEST->szUrl non-const? Netlib shouldn't (and doesn't IIRC) write to it, just read.

**Comment by White-Tiger** [comment]
well... I'm really not sure how it's internally... from another look at it, it seemed like Netlib free's NETLIBHTTPREQUEST->szUrl at some point so it should point to dynamically allocated memory... Something that SendSS didn't / doesn't use so it's a wonder it didn't crash by now...

Could need some clarification here though... and Doxygen comments on struct declaration / function usages etc. _(prevents mistakes and IDE's can use it to offer completion tooltips with inbuild documentation)_

**Comment by georgehazan** [comment]
@tweimer because netlib can change this url

**Comment by White-Tiger** [comment]
in that case.. SendSS had been "broken" for quite some time, yet still worked somehow^^

So... **what** exactly is `NETLIBHTTPREQUEST->szUrl`?
mir_alloc'd pointer which automatically frees on netlib close / `Netlib_FreeHttpRequest()` ?

How about some documentation to prevent confusion _(and also simplify contributions)_

**Comment by georgehazan** [comment]
some buffer allocated by netlib. Miranda frees it automatically when you close the netlib handle.

**Pull request merged**
