### PR TITLE
re-import libmdbx as git-subtree

### PR DESCRIPTION
**Pull request by leo-yuriev**
1. libmdbx (the master branch) added as git-subtree.
2. old/obsolete sources was dropped.
3. libmdbx builded as a static library:
   - this is more convenient for mdbx-tools (`mdbx_chk`, `mdbx_copy`, `mdbx_dump`, `mdbx_load`), which may be used separately in this case without dll-dependency.
   - no exra `libmbx.mir` file.
   - mdbx-database plugin now incorporates MDBX engine with explicit DllMain (no problems with DLL-unloading and Thread-Local-Storage destructors).
4. Add `mdbx_chk` and `mdbx_copy` tools.
5. Corresponding `*.vcxproj` files and `bin15/miranda32.sln` was updated.

**TODO/FIXME**: Update other sln-files: `bin15/mir_full.sln`, `bin16/miranda32.sln`, `bin16/mir_full` (`mdbx_chk.vcxproj` and `mdbx_copy.vcxproj` should be added).

### CODE REVIEW

**Comment by leo-yuriev** [comment]
In continue of https://forum.miranda-ng.org/index.php?topic=5542.msg25330#msg25330

**Comment by georgehazan** [comment]
no, subtree for us is not an option
merged 0.3.2 completely. seems to work ok

**Comment by leo-yuriev** [comment]
> no, subtree for us is not an option

In such case, please, remove completely libmdbx from Miranga-NG.

**Comment by georgehazan** [comment]
Well, git sucks, as I stated in the forum comments. making a link to libmdbx means that I can't make a stable & development biulds  from the same folder, thus crushing the whole system of releasing Miranda. Evidently, I won't do that, because I can't touch the source code of libmdbx used to build stable versions - I need to have two different copies of libmdbx sources & the simple alternative of having failed git on switching branches and damaged build system. Everything else is up to you, of course, I'm responsible of merging libmdbx sources by requests, that is the maximum I can offer

**Pull request closed without merging**
