### PR TITLE
KeepStatus, StartupStatus and AdvanceAutoAway merged into one plugin

### PR DESCRIPTION
**Pull request by aunsane**

### CODE REVIEW

**Comment by Robyer** [comment]
Does this change still keep these plugins separated? Because it is essential to be able to use only one of them. There are many variants of autoaway/startupstatus plugins, and users often want to use only Keep Status without AAA or Startupstatus.

**Comment by georgehazan** [comment]
no, there's the only StdAway that could be used instead of AAA, the same story with StartupStatus

**Comment by Robyer** [comment]
No, that's just completely wrong.

* Difference between StdAway & AAA is certainly NOT only one option. AAA is much much more advanced/customizable than StdAway. Perhaps you are talking about StdIdle.

* There is also plugin "SmartAutoAway" that I already adopted many months ago, but somehow it wasn't integrated in main repository. This plugin replaces StdAway and also KeepStatus (but NOT StartupStatus).

* "Startup Status" function is also in plugin "Simple Status Message".

**Comment by Robyer** [comment]
Merging this just breaks customizability and forces users to use either all these 3 plugins at once, or none of them. And that's just so wrong.

For example look at how many users use these plugins together already:
* http://vi.miranda-ng.org/cs/stats?filter=Keep+status
* only 70 % of them use Keep Status with Startup Status
* **only 28 % of them use Keep Status with AAA**

**Comment by White-Tiger** [comment]
well... user who don't use them, might simply be unaware of their very existence but could need them if they knew.
I'm not happy about Miranda's recent bloat _(in many ways)_ but I do think it's a good idea to have these by default...

Miranda in its default, unconfigured version, never looked really appealing to the average user... Not only because of its blunt look, but also for the seemingly lack of features *(which isn't true as we know)*
* Keep status: is mandatory if you ask me, what good is an IM when you're offline all the time because servers went down?
* Startup status: also quite mandatory... "global status" looks a bit like a hidden "feature" and I've only learned about it in recent times. *(from Miranda NG forums or issues, only because I'm involved)* Yet it also allows you to configure profiles and have different statuses for different protocols
* Advanced Auto Away: ok.. this is for those who want more advanced stuff :P But it's cool stuff to have it properly configured.

**Pull request merged**
