### PR TITLE
[IRCG] Addendum to 480f2c3: use m_userID instead of m_name on AUTHENTICATE and send CAP END afterwards. #1069

### PR DESCRIPTION
**Pull request by AmineKhaldi**
Thank you @georgehazan for working on this.

### CODE REVIEW

**Comment by georgehazan** [comment]
thanks alot for the patch. merged

**Comment by georgehazan** [comment]
I wonder how does it work though...
> [18:22:50 3884] [IRC_1] (000000000B847780:2004) Data sent
> CAP END
> [18:22:50 3884] [IRC_1] (000000000B847780:2004) Data received
> :weber.freenode.net 906 gtest :SASL authentication aborted
> [18:22:50 3884] [IRC_1] (000000000B847780:2004) Data received
> :weber.freenode.net 001 gtest :Welcome to the freenode Internet Relay Chat Network gtest
> :weber.freenode.net 002 gtest :Your host is weber.freenode.net[162.213.39.42/6667], running version ircd-seven-1.1.4

**Comment by georgehazan** [comment]
906 aka ERR_SASLABORTED is sent when the SASL authentication is aborted because the client sent an AUTHENTICATE command with * as the parameter.

:server 906 <nick> :SASL authentication aborted

**Comment by georgehazan** [comment]
@AmineKhaldi do you understand anything? :)

**Comment by AmineKhaldi** [comment]
I couldn't see from the log snippet that you provided, what led to AUTHENTICATE *, so I setup failure and success cases with the back and forth between client and server, and I sent you the results privately.
We follow that chain in our implementation, and we should then have a working solution that covers both.

**Comment by georgehazan** [comment]
there's definitely no AUTHENTICATE * from my side, just usual
<AUTHENTICATE PLAIN
>AUTHENTICATE +
<AUTHENTICATE blablabla

**Pull request merged**
